# Generated by Django 5.2.7 on 2025-10-22 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome do Computador')),
                ('ip_lm_studio', models.GenericIPAddressField(blank=True, null=True, verbose_name='LM-Studio')),
                ('placa_de_video', models.CharField(max_length=150, verbose_name='Placa de Vídeo')),
                ('id_anydesk', models.CharField(blank=True, max_length=50, null=True, verbose_name='AnyDesk')),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('M', 'Manutenção'), ('O', 'Ocupado (em Agendamento)')], default='D', max_length=1, verbose_name='Status de Uso')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.DateTimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.DateTimeField(verbose_name='Horário Final')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='Mapeamento.computador', verbose_name='Computador Agendado')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
