# Generated by Django 5.2.7 on 2026-09-30 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def resetar_status_ocupado(apps, schema_editor):
    """'Ocupado' deixou de ser um valor gravado e passa a ser calculado.

    Computadores que estejam com status='O' no banco (porque um admin marcou
    manualmente na lista do Django Admin) voltam para 'D' (Disponível).
    Sem isso esses equipamentos ficariam travados como "Ocupado" para sempre.
    """
    Computador = apps.get_model('Mapeamento', 'Computador')
    Computador.objects.filter(status='O').update(status='D')


def cancelar_agendamentos_invalidos(apps, schema_editor):
    """Repara dados legados que violam a nova restrição de horário.

    A view antiga NÃO validava "início < fim": as validações do ModelForm nunca
    eram chamadas, então o banco pode conter linhas com horario_fim <= horario_inicio.
    Sem este reparo o AddConstraint abaixo aborta a migração inteira com
    "check constraint is violated by some row".

    Em vez de apagar o histórico, os registros viram cancelados — eles param de
    reservar horário e ficam visíveis para auditoria.
    """
    Agendamento = apps.get_model('Mapeamento', 'Agendamento')
    invalidos = Agendamento.objects.filter(horario_fim__lte=F('horario_inicio'))
    total = invalidos.count()
    if not total:
        return
    invalidos.update(cancelado=True, data_cancelamento=django.utils.timezone.now())
    print(
        f'  [Mapeamento] {total} agendamento(s) com horário inválido foram '
        f'marcados como cancelados. Revise-os no Django Admin.'
    )


def restaurar_status_ocupado(apps, schema_editor):
    """Reversão: devolve 'O' para quem estava ocupado. Dados aproximados,
    apenas para que o rollback não deixe o campo inválido."""


class Migration(migrations.Migration):

    dependencies = [
        ('Mapeamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['horario_inicio', 'horario_fim'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Alteração'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Cancelamento'),
        ),
        migrations.RunPython(resetar_status_ocupado, restaurar_status_ocupado),
        migrations.RunPython(cancelar_agendamentos_invalidos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='agendamento',
            name='computador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='Mapeamento.computador', verbose_name='Computador Agendado'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('M', 'Manutenção')], default='D', max_length=1, verbose_name='Status de Uso'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['computador', 'horario_inicio'], name='Mapeamento__computa_5b4a38_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['cancelado'], name='Mapeamento__cancela_5b05b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('horario_fim__gt', models.F('horario_inicio')), ('cancelado', True), _connector='OR'), name='agendamento_fim_depois_do_inicio'),
        ),
    ]
