# Generated by Django 5.2.7 on 2026-10-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapeamento', '0002_soft_delete_e_status_dinamico'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, verbose_name='Chave')),
                ('janela_inicio', models.DateTimeField(verbose_name='Início da Janela')),
                ('contagem', models.PositiveIntegerField(default=0, verbose_name='Contagem')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tentativa de Rate Limit',
                'verbose_name_plural': 'Tentativas de Rate Limit',
                'ordering': ['-janela_inicio'],
                'indexes': [models.Index(fields=['janela_inicio'], name='Mapeamento__janela__idx')],
                'constraints': [models.UniqueConstraint(fields=('chave', 'janela_inicio'), name='tentativa_chave_janela_unica')],
            },
        ),
    ]
