"""
Django settings for liaancore project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from email.utils import parseaddr
from pathlib import Path
from dotenv import load_dotenv

from django.core.exceptions import ImproperlyConfigured

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Aceita '1', 'true', 'True', 'yes' (case-insensitive) para não quebrar
# ambientes que ainda usam DEBUG=1 (ver README).
DEBUG = os.environ.get('DEBUG', '0').strip().lower() in ('1', 'true', 'yes', 'on')

# Chave que assina sessão, cookie e CSRF. Lida ANTES do DEBUG porque a
# validação abaixo depende dele.
#
# Em produção ela é OBRIGATÓRIA. Antes havia um valor de fallback fixo no
# código — ou seja, no histórico do git — e o Django subia com ele quando a
# variável faltava. Qualquer pessoa com o repositório conseguiria forjar um
# cookie de sessão e se passar por qualquer usuário, inclusive admin.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "Defina a variável de ambiente SECRET_KEY. Sem ela o Django não "
            "sobe em produção (DEBUG=0): a chave pública versionada permitiria "
            "forjar sessões. Gere uma com: "
            "python -c \"from django.core.management.utils import "
            "get_random_secret_key as g; print(g())\""
        )
    # Só em desenvolvimento local, para o projeto subir sem configuração.
    SECRET_KEY = 'chave_insegura_para_desenvolvimento_local'

DATE_INPUT_FORMATS = ['%Y-%m-%d']
DATETIME_INPUT_FORMATS = ['%Y-%m-%dT%H:%M']

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '[::1]']

# Domínios extras vindos do ambiente, separados por vírgula.
# Exemplo no Render: ALLOWED_HOSTS="liaancore.onrender.com,laboratorio.iac.gov.br"
for host in os.environ.get('ALLOWED_HOSTS', '').split(','):
    host = host.strip()
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Sem ALLOWED_HOSTS explícito, em produção, usamos o host do RENDER_EXTERNAL_URL
# (que o Render define para todo web service).
#
# Antes havia um fallback para o curinga '.onrender.com', que aceitava QUALQUER
# subdomínio do Render no header Host. Isso abre brecha de host-header
# injection: basta o atacante mandar um Host arbitrário *.onrender.com para a
# validação passar. Não existe cenário legítimo em que o app precise aceitar
# domínios que não sejam o dele, então o curinga saiu: sem host definido, o
# Django não sobe.
if not DEBUG and not os.environ.get('ALLOWED_HOSTS'):
    host_do_render = os.environ.get('RENDER_EXTERNAL_URL', '').split('//')[-1].split('/')[0]
    if not host_do_render:
        raise ImproperlyConfigured(
            "Defina ALLOWED_HOSTS (ou deixe o Render definir RENDER_EXTERNAL_URL). "
            "Sem nenhum dos dois o Django não sobe em produção (DEBUG=0): aceitar "
            "um curinga como '.onrender.com' deixaria o cabeçalho Host ser forjado."
        )
    ALLOWED_HOSTS.append(host_do_render)

# Se estiver em produção (DEBUG=False), configure o SSL
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HSTS: o navegador passa a recusar HTTP por um ano. Só habilite se o
    # domínio já for 100% HTTPS — ativar isso em um host que ainda aceita
    # HTTP pode-travar o acesso de forma difícil de reverter.
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Application definition

# ModelBackend padrão: rejeita usuarios com is_active=False.
# A tela de login dá a mensagem amigável de "aguardando aprovação".
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

INSTALLED_APPS = [
    # Substitui 'django.contrib.admin': mesma app, mas com o AdminSite do
    # LiaanCore (que tem rate limit no login). Ver liaancore/apps.py.
    'liaancore.apps.LiaanCoreAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Mapeamento',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

DB_OPTIONS = {}

# Em produção o Postgres (Supabase) exige SSL.
# `require` criptografa o tráfego sem validar o certificado — necessário porque
# o Supabase assina com CA própria, que não está na cadeia padrão do sistema.
# Troque por `verify-full` se você distribuir a CA do Supabase na imagem.
# Configurável porque o Postgres do docker-compose local não usa SSL.
# Usa o DEBUG já parseado acima — nunca o valor cru da variável de ambiente.
if not DEBUG:
    DB_OPTIONS["sslmode"] = os.environ.get("DB_SSLMODE", "require")

# Agora, use essas opções no DATABASES
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "postgres"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": DB_OPTIONS,
        # O pool do Supabase é limitado e cada worker do Gunicorn segura
        # conexões. Reusar a conexão por 60s evita reabrir a cada requisição
        # sem segurar o pool aberto indefinidamente.
        "CONN_MAX_AGE": int(os.getenv("CONN_MAX_AGE", "60")),
        # Faz o Django validar a conexão ociosa antes de reciclá-la: uma
        # conexão morta pelo pooler não pode virar erro 500 para o usuário.
        "CONN_HEALTH_CHECKS": True,
    }
}


ROOT_URLCONF = 'liaancore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'liaancore.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

APPEND_SLASH = True

# --- REDIRECIONAMENTOS DE LOGIN ATUALIZADOS ---

# 1. Para onde ir após logar com sucesso (Painel de agendamentos)
LOGIN_REDIRECT_URL = 'mapeamento:home' 

# 2. Para onde ir após clicar em sair/logout (Sempre volta para a tela de login)
LOGOUT_REDIRECT_URL = 'login' 

# 3. Se um usuário não logado tentar entrar em /agendamento, o @login_required joga ele para cá:
LOGIN_URL = '/accounts/login/'

# Configurações de E-mail: o envio real é feito pela API do Resend (ver signup_view).
# O backend nativo do Django fica em modo console para Depuração local.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

RESEND_API_KEY = os.environ.get('RESEND_API_KEY')
LIAAN_ADMIN_EMAIL = os.environ.get('LIAAN_ADMIN_EMAIL')

# Remetente do aviso de novo cadastro.
#
# O padrão `onboarding@resend.dev` só funciona para o e-mail dono da conta
# Resend: a Resend rejeita esse remetente quando o destinatário é outra
# pessoa. Ou seja, em produção ele só funciona por acidente — e a falha era
# engolida num `print`. Com um domínio verificado (RESEND_FROM_EMAIL) o envio
# passa a valer de fato.
RESEND_FROM_EMAIL = os.environ.get(
    'RESEND_FROM_EMAIL', 'LiaanCore <onboarding@resend.dev>'
)

# Janela (em segundos) e número máximo de tentativas.
#
# RATE_LIMIT_LOGIN_POR_USUARIO é o que realmente fecha a força bruta: ele não
# depende de IP nem de header, então girar endereço não ajuda. As janelas
# curtas e o teto alto são para que travar a conta de alguém com um DoS
# precise de esforço parecido ao de adivinhar a senha.
RATE_LIMIT_CADASTRO = (3600, 5)
RATE_LIMIT_LOGIN = (300, 10)
RATE_LIMIT_LOGIN_POR_USUARIO = (300, 15)
RATE_LIMIT_LOGIN_ADMIN = (300, 10)

# Quem recebe o relatório de erro do Django (mail_admins). Vários destinatários
# no formato do email, separados por vírgula:
#   DJANGO_ADMINS='Nome <a@b.com>, Outro <c@d.com>'
#
# `parseaddr` é o que separa o nome do endereço; cortar a vírgula na mão
# deixaria o "<a@b.com>" dentro do endereço e o e-mail sairia inválido.
DJANGO_ADMINS = []
for _admin in os.environ.get('DJANGO_ADMINS', '').split(','):
    _nome, _email = parseaddr(_admin.strip())
    if _email:
        DJANGO_ADMINS.append((_nome, _email))

ADMINS = DJANGO_ADMINS

# Logging: sem isto, os erros iam por `print` e sumiam no meio do output do
# Gunicorn, sem nível, sem traceback estruturado e sem forma de alerta.
#
# O console em produção é intencional: no Render os logs do serviço são
# coletados por ali, e arquivo local não sobrevive ao próximo deploy (o disco é
# efêmero).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simples': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simples',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # O painel faz polling a cada 5s. Em INFO cada requisição viraria uma
        # linha de log e o histórico inteiro seria ruído.
        'django.server': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'liaancore': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# Internationalization

# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL base para os estáticos
STATIC_URL = 'static/'

# Diretório onde os arquivos estáticos serão coletados pelo collectstatic
# É esta pasta que o WhiteNoise irá servir em produção
STATIC_ROOT = BASE_DIR / 'staticfiles'

# APP_DIRS=True (acima) já encontra Mapeamento/static/ sozinho. Listar a mesma
# pasta aqui fazia o collectstatic achar cada arquivo duas vezes e avisar
# "Found another file with the destination path" a cada build.
STATICFILES_DIRS = []

# Armazenamento dos estáticos servido pelo WhiteNoise em produção.
# (A opção antiga STATICFILES_STORAGE foi removida no Django 5.1+.)
# Em DEBUG usamos o storage simples: o backend com manifest exige que
# `collectstatic` já tenha rodado e quebra o runserver/testes.
if DEBUG:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Cache: nenhuma configuração é necessária. O rate limiting usa o Postgres
# (modelo TentativaRateLimit), justamente para não depender de um cache
# compartilhado — o LocMem do Django é por processo e o Redis seria mais uma
# peça de infraestrutura só para guardar um contador.

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
