# """
# Django settings for liaancore project.

# Generated by 'django-admin startproject' using Django 5.2.7.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# import os
# import dj_database_url
# from pathlib import Path
# from dotenv import load_dotenv
# # from supabase import create_client, Client

# load_dotenv()

# # SUPABASE_URL = os.getenv("SUPABASE_URL")
# # SUPABASE_KEY = os.getenv("SUPABASE_KEY")

# # supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)



# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.environ.get('SECRET_KEY', 'chave_insegura_para_desenvolvimento_local')

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.environ.get('DEBUG', '0') == '1'

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.vercel.app']

# DATE_INPUT_FORMATS = ['%Y-%m-%d']
# DATETIME_INPUT_FORMATS = ['%Y-%m-%dT%H:%M']

# # ✅ CORREÇÃO PARA VERCEL
# VERCEL_URL = os.environ.get('VERCEL_URL')
# if VERCEL_URL:
#     # A Vercel envia a URL completa (ex: nome-do-projeto.vercel.app)
#     # Adicionamos o domínio base e o wildcard para subdomínios (deploy previews)
#     ALLOWED_HOSTS.append(VERCEL_URL)
#     ALLOWED_HOSTS.append(f'*.{VERCEL_URL}')
#     # Se você usar domínios personalizados, eles virão na variável DOMAIN
    
#     # Se o VERCEL_URL está definido, assumimos que estamos em produção
#     SECURE_SSL_REDIRECT = True
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'Mapeamento',
#     'django_extensions',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# if os.getenv('DATABASE_URL'):
#     # Se sim, usa o PostgreSQL
#     DATABASES = {
#         'default': dj_database_url.config(conn_max_age=600)
#     }
#     # Força o Django a usar a conexão HTTPS em produção
#     SECURE_SSL_REDIRECT = True
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
# else:
#     # Se não, usa o SQLite para desenvolvimento local
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }

# ROOT_URLCONF = 'liaancore.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'liaancore.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'pt-br'

# TIME_ZONE = 'America/Sao_Paulo'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# # URL base para os estáticos
# STATIC_URL = 'static/'

# # Diretório onde os arquivos estáticos serão coletados pelo collectstatic
# # É esta pasta que o WhiteNoise irá servir em produção
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# # Diretórios onde o Django procura arquivos estáticos (seus CSS/JS da app Mapeamento)
# STATICFILES_DIRS = [
#     BASE_DIR / "Mapeamento/static",
# ]

# # Configura o armazenamento do WhiteNoise para comprimir e cachear estáticos
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



"""
Django settings for liaancore project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'chave_insegura_para_desenvolvimento_local')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

DATE_INPUT_FORMATS = ['%Y-%m-%d']
DATETIME_INPUT_FORMATS = ['%Y-%m-%dT%H:%M']

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Adiciona a URL de produção (Render) automaticamente
RENDER_EXTERNAL_URL = os.environ.get('RENDER_EXTERNAL_URL')
if RENDER_EXTERNAL_URL:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_URL.split('//')[-1]) # Remove o 'https://'

# Se estiver em produção (DEBUG=False), configure o SSL
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Mapeamento',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

DB_OPTIONS = {}

# Se NÃO estivermos em modo DEBUG (ou seja, em produção na Vercel)
if not os.getenv("DEBUG"):
    DB_OPTIONS["sslmode"] = "require"

# Agora, use essas opções no DATABASES
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "postgres"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": DB_OPTIONS  # <-- Aqui está a mágica!
    }
}


ROOT_URLCONF = 'liaancore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'liaancore.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --- REDIRECIONAMENTOS DE LOGIN ---

# 1. Para onde ir após um LOGIN bem-sucedido
# (Aponta para o name='home' dentro do app_name='mapeamento')
LOGIN_REDIRECT_URL = 'mapeamento:home' 

# 2. Para onde ir após um LOGOUT
# (Aponta de volta para a página de login, a raiz '/')
LOGOUT_REDIRECT_URL = 'login' 

# 3. Onde encontrar a página de login
# (Se o @login_required for ativado, ele envia o usuário para cá)
LOGIN_URL = 'login'
# Internationalization

# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL base para os estáticos
STATIC_URL = 'static/'

# Diretório onde os arquivos estáticos serão coletados pelo collectstatic
# É esta pasta que o WhiteNoise irá servir em produção
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Diretórios onde o Django procura arquivos estáticos (seus CSS/JS da app Mapeamento)
STATICFILES_DIRS = [
    BASE_DIR / "Mapeamento/static",
]

# Configura o armazenamento do WhiteNoise para comprimir e cachear estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
