"""
Django settings for liaancore project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'chave_insegura_para_desenvolvimento_local')

# SECURITY WARNING: don't run with debug turned on in production!
# Aceita '1', 'true', 'True', 'yes' (case-insensitive) para não quebrar
# ambientes que ainda usam DEBUG=1 (ver README).
DEBUG = os.environ.get('DEBUG', '0').strip().lower() in ('1', 'true', 'yes', 'on')

DATE_INPUT_FORMATS = ['%Y-%m-%d']
DATETIME_INPUT_FORMATS = ['%Y-%m-%dT%H:%M']

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '[::1]']

# Domínios extras vindos do ambiente, separados por vírgula.
# Exemplo no Render: ALLOWED_HOSTS="liaancore.onrender.com,laboratorio.iac.gov.br"
for host in os.environ.get('ALLOWED_HOSTS', '').split(','):
    host = host.strip()
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Fallback para o Render: evita HTTP 400 em produção caso o ambiente
# não defina RENDER_EXTERNAL_URL nem ALLOWED_HOSTS.
if not DEBUG and not os.environ.get('ALLOWED_HOSTS'):
    RENDER_EXTERNAL_URL = os.environ.get('RENDER_EXTERNAL_URL', '')
    # Remove o esquema e qualquer barra/caminho residual.
    host_padrao = RENDER_EXTERNAL_URL.split('//')[-1].split('/')[0]
    ALLOWED_HOSTS.append(host_padrao or '.onrender.com')

# Se estiver em produção (DEBUG=False), configure o SSL
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HSTS: o navegador passa a recusar HTTP por um ano. Só habilite se o
    # domínio já for 100% HTTPS — ativar isso em um host que ainda aceita
    # HTTP pode-travar o acesso de forma difícil de reverter.
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Application definition

# ModelBackend padrão: rejeita usuarios com is_active=False.
# A tela de login dá a mensagem amigável de "aguardando aprovação".
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Mapeamento',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

DB_OPTIONS = {}

# Em produção o Postgres (Supabase Pooler) exige SSL.
# Usa o DEBUG já parseado acima — nunca o valor cru da variável de ambiente.
if not DEBUG:
    DB_OPTIONS["sslmode"] = "require"

# Agora, use essas opções no DATABASES
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "postgres"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": DB_OPTIONS
    }
}


ROOT_URLCONF = 'liaancore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'liaancore.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

APPEND_SLASH = True

# --- REDIRECIONAMENTOS DE LOGIN ATUALIZADOS ---

# 1. Para onde ir após logar com sucesso (Painel de agendamentos)
LOGIN_REDIRECT_URL = 'mapeamento:home' 

# 2. Para onde ir após clicar em sair/logout (Sempre volta para a tela de login)
LOGOUT_REDIRECT_URL = 'login' 

# 3. Se um usuário não logado tentar entrar em /agendamento, o @login_required joga ele para cá:
LOGIN_URL = '/accounts/login/'

# Configurações de E-mail: o envio real é feito pela API do Resend (ver signup_view).
# O backend nativo do Django fica em modo console para Depuração local.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

RESEND_API_KEY = os.environ.get('RESEND_API_KEY')
LIAAN_ADMIN_EMAIL = os.environ.get('LIAAN_ADMIN_EMAIL')

# Janela (em segundos) e número máximo de tentativas por IP.
RATE_LIMIT_CADASTRO = (3600, 5)
RATE_LIMIT_LOGIN = (300, 10)

# Internationalization

# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL base para os estáticos
STATIC_URL = 'static/'

# Diretório onde os arquivos estáticos serão coletados pelo collectstatic
# É esta pasta que o WhiteNoise irá servir em produção
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Diretórios onde o Django procura arquivos estáticos (seus CSS/JS da app Mapeamento)
STATICFILES_DIRS = [
    BASE_DIR / "Mapeamento/static",
]

# Armazenamento dos estáticos servido pelo WhiteNoise em produção.
# (A opção antiga STATICFILES_STORAGE foi removida no Django 5.1+.)
# Em DEBUG usamos o storage simples: o backend com manifest exige que
# `collectstatic` já tenha rodado e quebra o runserver/testes.
if DEBUG:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Cache usado pelo rate limiting. Em produção com múltiplos workers/processos
# o LocMem NÃO é compartilhado: configure CACHE_URL (ex.: rediss://...) no Render
# e instale o pacote 'redis' (pip install redis) para habilitar o backend acima.
if os.environ.get('CACHE_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.environ['CACHE_URL'],
        }
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
